#!/bin/bash

################################################################################
# mutate.sh
#
# Overview
# ========
#
# This script automates the mutation testing process using certoraMutate.
# It validates prerequisites, generates/updates the mutation-enabled prover.conf,
# runs certoraMutate, and provides a summary of survivors with recommendations.
#
# Usage
# -----
#
# ./scripts/mutate.sh [--json <config_file>]
#
# Arguments:
#   --json <config_file>  Path to the JSON configuration file for mutation testing
#
################################################################################

set -e

# Get the directory where this script is located
SCRIPTS=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
GAMBIT="$SCRIPTS/.."

# Parse arguments
CONFIG_FILE=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --json)
            CONFIG_FILE="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1"
            echo "Usage: $0 [--json <config_file>]"
            exit 1
            ;;
    esac
done

# Validate that config file is provided
if [[ -z "$CONFIG_FILE" ]]; then
    echo "Error: --json argument is required"
    echo "Usage: $0 --json <config_file>"
    exit 1
fi

# Validate that config file exists
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Error: Config file '$CONFIG_FILE' does not exist"
    exit 1
fi

# Function to validate prerequisites
default_validate_prerequisites() {
    echo "Validating prerequisites..."
    
    # Check if certora-cli is installed
    if ! command -v certora-cli &> /dev/null; then
        echo "Error: certora-cli is not installed or not in PATH"
        echo "Please install certora-cli and ensure it's available in your PATH"
        exit 1
    fi
    echo "✓ certora-cli is installed"
    
    # Check if certoraMutate exists
    if ! command -v certoraMutate &> /dev/null; then
        echo "Error: certoraMutate is not installed or not in PATH"
        echo "Please install certoraMutate and ensure it's available in your PATH"
        exit 1
    fi
    echo "✓ certoraMutate is installed"
    
    # Check if gambit exists (built)
    if ! command -v gambit &> /dev/null; then
        echo "Error: gambit is not built or not in PATH"
        echo "Please build gambit first using 'cargo build'"
        exit 1
    fi
    echo "✓ gambit is available"
}

# Function to generate/update mutation-enabled prover.conf
default_generate_prover_conf() {
    echo "Generating/updating mutation-enabled prover.conf..."
    
    # Extract contract name from config file
    CONTRACT_NAME=$(jq -r '.contract_name' "$CONFIG_FILE")
    if [[ "$CONRACT_NAME" == "null" || -z "$CONTRACT_NAME" ]]; then
        echo "Warning: Could not extract contract_name from config, using default"
        CONTRACT_NAME="MyContract"
    fi
    
    # Extract filename from config file
    FILENAME=$(jq -r '.filename' "$CONFIG_FILE")
    if [[ "$FILENAME" == "null" || -z "$FILENAME" ]]; then
        echo "Error: Could not extract filename from config"
        exit 1
    fi
    
    # Create prover.conf with mutation testing settings
    PROVER_CONF="prover.conf"
    cat > "$PROVER_CONF" << EOF
# Mutation testing configuration for Certora Prover
# Generated by gambit mutate script

# Basic settings
contract = $CONTRACT_NAME
filename = $FILENAME

# Mutation testing specific settings
mutations = true
mutation_operators = [
    "binary_operator",
    "unary_operator", 
    "require_statement",
    "assignment",
    "function_call",
    "if_statement",
    "swap_arguments_function",
    "swap_arguments_operator",
    "swap_lines",
    "delete_expression",
    "eliminate_delegate"
]

# Enable detailed mutation reporting
mutation_report = true
mutation_report_format = json
mutation_report_file = mutation_results.json

# Set mutation testing mode
mutation_mode = all
mutation_timeout = 300

EOF
    
    echo "✓ Generated prover.conf at: $(pwd)/$PROVER_CONF"
}

# Function to run certoraMutate
default_run_certora_mutate() {
    echo "Running certoraMutate..."
    
    # Run certoraMutate with the generated configuration
    echo "Executing: certoraMutate --conf prover.conf"
    
    # Capture start time
    START_TIME=$(date +%s)
    
    # Run certoraMutate
    certoraMutate --conf prover.conf
    
    # Capture end time
    END_TIME=$(date +%s)
    
    echo "✓ certoraMutate completed in $((END_TIME - START_TIME)) seconds"
    echo "Results can be found in: $(pwd)/mutation_results.json"
}

# Function to summarize survivors and recommend spec improvements
default_summarize_results() {
    echo "Summarizing mutation testing results..."
    
    RESULTS_FILE="mutation_results.json"
    
    # Check if results file exists
    if [[ ! -f "$RESULTS_FILE" ]]; then
        echo "Warning: Could not find mutation results file: $RESULTS_FILE"
        echo "Mutation testing may not have completed successfully"
        return
    fi
    
    # Parse results to get survivor count and details
    TOTAL_MUTANTS=$(jq '.mutants | length' "$RESULTS_FILE" 2>/dev/null || echo "0")
    SURVIVORS=$(jq '[.mutants[] | select(.status == "SURVIVED")] | length' "$RESULTS_FILE" 2>/dev/null || echo "0")
    KILLED=$(jq '[.mutants[] | select(.status == "KILLED")] | length' "$RESULTS_FILE" 2>/dev/null || echo "0")
    
    echo "Mutation Testing Summary:"
    echo "========================"
    echo "Total mutants generated: $TOTAL_MUTANTS"
    echo "Mutants killed: $KILLED"
    echo "Mutants survived: $SURVIVORS"
    
    if [[ "$TOTAL_MUTANTS" -eq 0 ]]; then
        echo "Warning: No mutants were generated. Check your configuration."
        return
    fi
    
    # Calculate mutation score
    if [[ "$TOTAL_MUTANTS" -gt 0 ]]; then
        MUTATION_SCORE=$((100 * KILLED / TOTAL_MUTANTS))
        echo "Mutation score: $MUTATION_SCORE%"
    fi
    
    # Provide recommendations based on survivors
    if [[ "$SURVIVORS" -gt 0 ]]; then
        echo ""
        echo "Survivor Analysis:"
        echo "------------------"
        
        # Get survivor details
        SURVIVOR_DETAILS=$(jq -c '[.mutants[] | select(.status == "SURVIVED") | {mutant_id, operator, location, description}]' "$RESULTS_FILE")
        
        echo "$SURVIVOR_DETAILS" | jq -c '.[]' | while read -r survivor; do
            MUTANT_ID=$(echo "$survivor" | jq -r '.mutant_id')
            OPERATOR=$(echo "$survivor" | jq -r '.operator')
            LOCATION=$(echo "$survivor" | jq -r '.location')
            DESCRIPTION=$(echo "$survivor" | jq -r '.description')
            
            echo "Survivor #$MUTANT_ID:"
            echo "  Operator: $OPERATOR"
            echo "  Location: $LOCATION"
            echo "  Description: $DESCRIPTION"
            echo ""
        done
        
        echo "Recommendations for Specification Improvements:"
        echo "--------------------------------------------"
        echo "1. Review the survived mutants above - these indicate areas where your"
        echo "   specification may be incomplete or not sufficiently precise."
        echo "2. Add specific rules to catch these edge cases in your spec."
        echo "3. Consider adding more comprehensive invariants and assertions."
        echo "4. For arithmetic operators, add overflow/underflow checks."
        echo "5. For require statements, ensure all failure conditions are covered."
        echo "6. Review function call mutations to ensure proper authorization checks."
        echo ""
        echo "Example improvements:"
        echo "- Add explicit bounds checking for array accesses"
        echo "- Include more comprehensive state invariants"
        echo "- Add specific rules for edge cases in mathematical operations"
        echo "- Ensure all external calls have proper reentrancy protection"
    else
        echo ""
        echo "Excellent! All mutants were killed. Your specification appears to be comprehensive."
        echo "Continue maintaining this level of specification coverage."
    fi
}

# Main execution
main() {
    echo "Starting Gambit Mutation Testing..."
    echo "==================================="
    echo ""
    
    # Change to gambit directory
    cd "$GAMBIT" || {
        echo "Error: couldn't cd to $GAMBIT"
        exit 1
    }
    
    # Step 1: Validate prerequisites
    default_validate_prerequisites
    echo ""
    
    # Step 2: Generate/update prover.conf
    default_generate_prover_conf
    echo ""
    
    # Step 3: Run certoraMutate
    default_run_certora_mutate
    echo ""
    
    # Step 4: Summarize results
    default_summarize_results
    echo ""
    
    echo "Mutation testing process completed!"
}

# Run main function
main "$@"